### ISSUE TITLE
[PE-D][Tester D] Remnants of Persons in error messages

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T12-3/tp#176]
### Description

`delete` or `add` without the `-a` or `-i` tags leads to an error message referencing `Persons` although there is no mention of `Persons` in the app or the UG.

### Steps to reproduce

1. Call `delete`, `add`, `edit` or `find`

### Expected outcome

* Error message saying 'Unknown command'

### Actual outcome

* Error message saying 'Please switch to PERSONS before performing this operation using its respective list command'

### Screenshot

![image.png](https://raw.githubusercontent.com/tllshan/ped/main/files/e858a53f-8167-4b75-9801-db21bc4dcf33.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: tllshan/ped#8

**Comment by chuababyy** [comment]
done already
