### ISSUE TITLE
[PE-D][Tester D] Discrepancy between UG and app for editing 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T12-3/tp#183]
### Description

UG states `edit-i-role i/INDEX d/DESCRIPTION` as the input for the `Editing an internship task` command. However, on the app, the `edit-i-role i/INDEX` can be paired with other field tags to edit other fields. Perhaps indicating the optional fields in the UG will be more accurate.

### Steps to reproduce

1. Add internship role
1. Call `edit-i-role i/1 p/200`

### Expected outcome

* Error message

### Actual outcome

* Success message
* Internship role is edited

### Screenshot

![image.png](https://raw.githubusercontent.com/tllshan/ped/main/files/1ab9ce00-3cd7-431f-ad9b-c4fef71c0349.png)

![image.png](https://raw.githubusercontent.com/tllshan/ped/main/files/2dc037ae-9c8b-421e-9ff7-b8cd1a47090c.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: tllshan/ped#9

**Comment by Badatprogrammiing** [comment]
I think this guy forget to clear cache, but the purpose and maybe description needs to be updated
