### ISSUE TITLE
As a computer science student, I want to be able to easily add information about my current internship, including the company name, start date, end date, and key responsibilities.

### ISSUE THREAD

**Issue by seewhyjay** [AY2324S1-CS2103T-T12-3/tp#79]
So that I can easily know what has to be done and what stage each application is in and what each internship entails

**Comment by chuababyy** [comment]
`add-i-role n/<name of company> r/<role name> d/<description> p/<pay> o/<outcome> l/<location> a/<link>`

**Comment by chuababyy** [comment]
`add-i-task i/<index of company> t/<task name> e/<deadline> s/<status: complete/incomplete> o/<outcome>`
outcome: follow up, offered, ghosted, rejected ONLY

**Comment by Badatprogrammiing** [comment]
> `add-i-role n/<name of company> r/<role name> [d/<description>] [p/<pay>] [o/<outcome>] [l/<location>] [a/<link>]`
> 
> * outcome: follow up, offered, ghosted, rejected, accepted ONLY

 `add-i-role n/<name of company> r/<role name> c/<cycle> [d/<description>] [p/<pay>] [o/<outcome>] [l/<location>] `
