### ISSUE TITLE
As a computer science student, I want to track the status of my internship applications, including whether they are pending, accepted, or rejected, 

### ISSUE THREAD

**Issue by seewhyjay** [AY2324S1-CS2103T-T12-3/tp#85]
so that I can easily monitor the progress of my applications.

**Comment by chuababyy** [comment]
`edit-i-role i/<index of company> o/<outcome>` 
- outcome: follow up, offered, ghosted, rejected, accepted ONLY

**Comment by chuababyy** [comment]
`edit-i-task i/<index of task> o/<outcome>`
- outcome: follow up, offered, ghosted, rejected ONLY
